services:
  app:
    image: telaten-backend:latest
    container_name: telaten-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8065:8065"
    env_file:
      - .env
